### ISSUE TITLE
Deleting Profile Picture Breaks Profile

### ISSUE THREAD

**Issue by sjtolley9** [TheHuddle/website#16]
I was trying to delete my profile pic as part of implementing a default profile picture. After deleting my profile picture in the profile picture form, my profile wouldn't load correctly. A loading wheel remained on the page indefinitely, and the profile picture and information never loaded.

![deleted_profile](https://user-images.githubusercontent.com/46732240/149606319-5fa28396-be99-4222-b168-89958d66ae9e.png)

**Comment by sjtolley9** [comment]
Navigating to the page produced the following error:
```
core.mjs:6495 ERROR TypeError: Cannot read properties of null (reading 'id')
    at AssetsService.get (assets.service.ts:16)
    at ProfileComponent.refresh (component.ts:69)
    at component.ts:60
    at Object.next (Subscriber.js:110)
    at SafeSubscriber._next (Subscriber.js:60)
    at SafeSubscriber.next (Subscriber.js:31)
    at map.js:7
    at OperatorSubscriber._next (OperatorSubscriber.js:9)
    at OperatorSubscriber.next (Subscriber.js:31)
    at filter.js:6
```

**Comment by wrynegade** [comment]
This seems to be an issue with the assets service trying to return the "id" of a null object.

```javascript
  get(asset: any): string {
    if (typeof asset === 'string') {
      return `${environment.apiBase}/assets/${asset}`;
    } else {
      return `${environment.apiBase}/assets/${asset.id}`;
    }
  }

```
> https://github.com/TheHuddle/website/blob/8c434a6350327ec7c321d41a0ad3f83ac2b3dbcf/src/app/services/assets.service.ts#L12

A simple guard here should do the trick
