### ISSUE TITLE
Sort Tasks by Complete / Available / Historic

### ISSUE THREAD

**Issue by wrynegade** [TheHuddle/website#28]
We need to design a view which allows a user to filter by complete / available / unavailable tasks.

Clicking the Legend could trigger the sort / filter. A visual indicator on the current filter would be excellent.
![DeepinScreenshot_select-area_20220118195935](https://user-images.githubusercontent.com/35513193/150055676-f94d8d5e-faa3-4c5e-b269-e63906a1fbd6.png)

**Comment by Simponic** [comment]
I can take a crack at this @wrynegade!

**Comment by wrynegade** [comment]
Excellent! It's yours @Simponic . Do you need any pointers to get started?

**Comment by wrynegade** [comment]
Going to adjust the scope on this a bit:

Tasks page should only include tasks which are available to complete, leaving the user with tasks that are _either_ complete or incomplete. The material indicators should be sufficient to show whether a task is complete or not, so the header can be removed.

Let's  order tasks:
1. Incomplete
2. Complete, but repeatable
3. Complete

And rename the page from "Tasks" to "Todo"
